name: Run Arxiv Scraper

on:
  schedule:
    # Run every weekday (Monday through Friday) at 7:00 AM US Eastern Time
    - cron: "0 11 * * 1-5"  # UTC time for 7:00 AM ET on weekdays

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python astropy_scraping.py